### ISSUE TITLE
Switch to SQLite database

### ISSUE THREAD

**Issue by uzervlad** [SGezha/osu-youtube-music-player#2]
Firstly, JSON is just bad for databases. Secondly, it should increase performance, at least a little bit

**Comment by uzervlad** [comment]
better-sqlite made everything much worse, now I can't even run YOMP

**Comment by SGezha** [comment]
![image](https://user-images.githubusercontent.com/23618967/65505444-e9968e00-ded1-11e9-8f85-af54e114af1f.png)

@uzervlad
